# Generated by Django 5.0.2 on 2024-05-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectAnswers',
            fields=[
                ('correct_answers_i_d', models.AutoField(db_column='correct_answers_¦d', primary_key=True, serialize=False)),
                ('word_id', models.IntegerField(blank=True, null=True)),
                ('true_word', models.CharField(blank=True, max_length=63, null=True)),
                ('answer_date', models.DateField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'correct_answers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Kullanicibilgileri',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=75, null=True)),
                ('surname', models.CharField(blank=True, max_length=75, null=True)),
                ('username', models.CharField(blank=True, max_length=75, null=True)),
                ('user_mail', models.CharField(blank=True, max_length=45, null=True)),
                ('user_password', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'kullanicibilgileri',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('word_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=63, null=True)),
                ('true_word', models.CharField(blank=True, max_length=63, null=True)),
                ('false_word1', models.CharField(blank=True, max_length=63, null=True)),
                ('false_word2', models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                'db_table': 'words',
                'managed': True,
            },
        ),
    ]
