# Generated by Django 5.0.2 on 2024-05-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordDemo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctanswers',
            name='correct_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctanswers',
            name='next_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
